name: ease
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.5.3 <4.0.0'
dependencies:
  mime: ^2.0.0
  http: ^1.4.0
  flutter:
    sdk: flutter
  mailer: ^6.4.1
  cupertino_icons: ^1.0.6
  fluttertoast: ^8.2.5
  shared_preferences: ^2.5.1
  path: ^1.8.0
  path_provider: ^2.1.5
  icons_plus: ^5.0.0
  url_launcher: ^6.1.7
  google_sign_in: ^6.1.1
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  image_picker: ^1.1.2
  permission_handler: ^12.0.1
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.3
  intl: ^0.17.0
  firebase_auth: ^5.2.0
  google_maps_flutter: ^2.9.0
  location: ^8.0.1
  google_fonts: ^6.2.1
  flutter_spinkit: ^5.2.0
  animated_text_kit: ^4.2.2
  font_awesome_flutter: ^10.8.0
  confetti: ^0.8.0
  geolocator: ^14.0.2
  webview_flutter: ^4.9.0
  lottie: ^3.3.1
  http_parser: ^4.0.2
  share_plus: ^11.0.0
  firebase_performance: ^0.10.0+8
  flutter_tts: ^4.2.2
  carousel_slider: ^5.0.0
  geocoding: ^4.0.0
  youtube_player_flutter: ^9.1.1
  flutter_inappwebview: ^6.1.5
  image_compare_2: ^1.1.7
dependency_overrides:
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/happy_earth.gif
    - lib/assets/ease.jpg
    - lib/assets/loading.gif
    - lib/assets/banana.png
    - lib/assets/glass.png
    - lib/assets/paper.png
    - lib/assets/earth.gif
    - lib/assets/plasticbottle.png
    - lib/assets/yolov8n_float32.tflite
    - lib/assets/park.jpg
    - lib/assets/boy.jpg
    - lib/assets/eco.gif
    - lib/assets/fail.gif
    - lib/assets/success.gif
    - lib/assets/art1.jpg
    - lib/assets/art2.jpg
    - lib/assets/art3.jpg
    - lib/assets/earth.jpg
    - lib/assets/standboy.png
    - lib/assets/runboy.png
    - lib/assets/runningboy.png
    - lib/assets/sea.jpg

