name: ease
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.5.3 <4.0.0'
dependencies:
  mime: ^1.0.0
  http: ^0.13.3
  flutter:
    sdk: flutter
  mailer: ^4.0.0
  cupertino_icons: ^1.0.6
  fluttertoast: ^8.2.5
  shared_preferences: ^2.5.1
  path: ^1.8.0
  path_provider: ^2.1.5
  icons_plus: ^5.0.0
  url_launcher: ^6.1.7
  google_sign_in: ^6.0.0
  googleapis: ^11.0.0
  googleapis_auth: ^1.0.0
  image_picker: ^0.8.4+5
  permission_handler: ^11.3.1
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.3
  intl: ^0.17.0
  firebase_auth: ^5.2.0
  google_maps_flutter: ^2.9.0
  location: ^7.0.0
  google_fonts: ^4.0.4
  flutter_spinkit: ^5.2.0
  animated_text_kit: ^4.2.2
  font_awesome_flutter: ^10.8.0
  confetti: ^0.8.0
  geolocator: ^12.0.0
  webview_flutter: ^4.9.0
  lottie: ^2.7.0
  http_parser: ^4.0.2
  share_plus: ^10.1.3
  firebase_performance: ^0.10.0+8
  carousel_slider: ^5.0.0
  geocoding: ^2.1.0
dependency_overrides:
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/happy_earth.gif
    - lib/assets/ease.jpg

